# Generated by Django 3.1.7 on 2021-04-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='user/image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='admin/image')),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
